name: dukalipa_app
description: A shop management application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # Navigation
  go_router: ^10.0.0
  
  # Network
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  
  # UI
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  shimmer: ^2.0.0  # Add this line for shimmer loading effects
  cached_network_image: ^3.3.0
  intl: ^0.20.2
  lottie: ^2.7.0  # Add this line for Lottie animations
  
  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0

  # Dependency Injection
  get_it: ^7.6.0
  
  # Utils
  logger: ^2.0.1
  uuid: ^3.0.7
  image_picker: ^1.0.2
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  flutter_local_notifications: ^15.1.0+1

  # Charts
  fl_chart: ^0.66.0

  # JSON Serialization
  json_annotation: ^4.8.1

  # Icons
  lucide_icons: ^0.257.0

  # Reorderable Staggered Grid
  reorderable_staggered_scroll_view: ^0.0.2
  reorderable_staggered_grid_view: ^0.0.1+1
  flutter_staggered_grid_view: ^0.7.0
  reorderable_grid: ^1.0.10  # Add this new dependency

  flutter_screenutil: ^5.9.0  # Add this for responsive sizing
  table_calendar: ^3.0.0
  printing: ^5.14.2
  share_plus: ^11.0.0
  mobile_scanner: ^3.5.5
  dynamic_color: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/i18n/
    - assets/images/
    - assets/icons/
    - assets/animations/  # Make sure this line exists

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
